# Dependencies
markdown: kramdown
highlighter: rouge

# gems:                
plugins:             [jekyll-paginate,jekyll-gist]
# paginate:            5
# paginate_path:       "page:num"

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Krish Shah
tagline:          ''
description:      ''
url:              https://krish0706.github.io
baseurl:          "/"

author:
  name:           'Krish Shah'


# Custom vars
# version:          2.1.0

github:           
  repo:           https://krish0706.github.io/
